spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: upadate
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

    logging:
      level:
        root: DEBUG
        org.springframework.security: DEBUG
